version: "3.8"
services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    depends_on:
      - db
    ports:
      - "8080:80"            
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=dvwa_password
      - MYSQL_DATABASE=dvwa
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: dvwa_db
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=dvwa_password
    volumes:
      - dvwa_mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dvwa_phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOST=db
    ports:
      - "8082:80"            
    restart: unless-stopped

volumes:
  dvwa_mysql_data:
